"""Add table for tracking ECS Guacamole sessions

Revision ID: 0012477fe0a8
Revises: 6f2773029d86
Create Date: 2023-03-17 14:31:57.957974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0012477fe0a8"
down_revision = "6f2773029d86"
branch_labels = None
depends_on = None


def upgrade(op=None):
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ecs_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("recording_uuid", sa.Text(), nullable=True),
        sa.Column("challenge_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ecs_history_id"), "ecs_history", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade(op=None):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ecs_history_id"), table_name="ecs_history")
    op.drop_table("ecs_history")
    # ### end Alembic commands ###
