"""Initial revision for the ECS Challenge plugin database

Revision ID: 15277440466a
Revises: None
Create Date: 2023-02-17 11:35:10.395321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "15277440466a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade(op=None):
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ecs_challenge_tracker",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column(
            "owner_id",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=64),
            nullable=True,
        ),
        sa.Column(
            "task_definition",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=128),
            nullable=True,
        ),
        sa.Column(
            "challenge_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "timestamp",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "revert_time",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "instance_id",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=128),
            nullable=True,
        ),
        sa.Column(
            "ports",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=128),
            nullable=True,
        ),
        sa.Column(
            "host",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=128),
            nullable=True,
        ),
        sa.Column(
            "flag",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=128),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_ecs_challenge_tracker_timestamp",
        "ecs_challenge_tracker",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_ecs_challenge_tracker_task_definition",
        "ecs_challenge_tracker",
        ["task_definition"],
        unique=False,
    )
    op.create_index(
        "ix_ecs_challenge_tracker_revert_time",
        "ecs_challenge_tracker",
        ["revert_time"],
        unique=False,
    )
    op.create_index(
        "ix_ecs_challenge_tracker_ports",
        "ecs_challenge_tracker",
        ["ports"],
        unique=False,
    )
    op.create_index(
        "ix_ecs_challenge_tracker_owner_id",
        "ecs_challenge_tracker",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        "ix_ecs_challenge_tracker_instance_id",
        "ecs_challenge_tracker",
        ["instance_id"],
        unique=False,
    )
    op.create_index(
        "ix_ecs_challenge_tracker_host", "ecs_challenge_tracker", ["host"], unique=False
    )
    op.create_index(
        "ix_ecs_challenge_tracker_flag", "ecs_challenge_tracker", ["flag"], unique=False
    )
    op.create_index(
        "ix_ecs_challenge_tracker_challenge_id",
        "ecs_challenge_tracker",
        ["challenge_id"],
        unique=False,
    )
    op.create_table(
        "ecs_config",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column(
            "repositories", mysql.TEXT(collation="utf8mb4_unicode_ci"), nullable=True
        ),
        sa.Column(
            "active_vpc",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=64),
            nullable=True,
        ),
        sa.Column(
            "aws_access_key_id",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=20),
            nullable=True,
        ),
        sa.Column(
            "aws_secret_access_key",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=40),
            nullable=True,
        ),
        sa.Column(
            "cluster",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=128),
            nullable=True,
        ),
        sa.Column("subnets", mysql.TEXT(collation="utf8mb4_unicode_ci"), nullable=True),
        sa.Column(
            "security_groups", mysql.TEXT(collation="utf8mb4_unicode_ci"), nullable=True
        ),
        sa.Column(
            "region",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=32),
            nullable=True,
        ),
        sa.Column(
            "guacamole_address",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=128),
            nullable=True,
        ),
        sa.Column(
            "guacamole_json_secret_key",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=128),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_ecs_config_active_vpc", "ecs_config", ["active_vpc"], unique=False
    )
    op.create_table(
        "ecs_challenge",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=False, nullable=False
        ),
        sa.Column(
            "task_definition",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=128),
            nullable=True,
        ),
        sa.Column(
            "subnet",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=128),
            nullable=True,
        ),
        sa.Column(
            "security_group",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=128),
            nullable=True,
        ),
        sa.Column(
            "entrypoint_container",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=128),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["id"], ["challenges.id"], name="ecs_challenge_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_ecs_challenge_task_definition",
        "ecs_challenge",
        ["task_definition"],
        unique=False,
    )
    op.create_index(
        "ix_ecs_challenge_subnet", "ecs_challenge", ["subnet"], unique=False
    )
    op.create_index(
        "ix_ecs_challenge_security_group",
        "ecs_challenge",
        ["security_group"],
        unique=False,
    )
    op.create_index(
        "ix_ecs_challenge_entrypoint_container",
        "ecs_challenge",
        ["entrypoint_container"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade(op=None):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ecs_challenge_entrypoint_container", table_name="ecs_challenge")
    op.drop_index("ix_ecs_challenge_security_group", table_name="ecs_challenge")
    op.drop_index("ix_ecs_challenge_subnet", table_name="ecs_challenge")
    op.drop_index("ix_ecs_challenge_task_definition", table_name="ecs_challenge")
    op.drop_table("ecs_challenge")
    op.drop_index("ix_ecs_config_active_vpc", table_name="ecs_config")
    op.drop_table("ecs_config")
    op.drop_index(
        "ix_ecs_challenge_tracker_challenge_id", table_name="ecs_challenge_tracker"
    )
    op.drop_index("ix_ecs_challenge_tracker_flag", table_name="ecs_challenge_tracker")
    op.drop_index("ix_ecs_challenge_tracker_host", table_name="ecs_challenge_tracker")
    op.drop_index(
        "ix_ecs_challenge_tracker_instance_id", table_name="ecs_challenge_tracker"
    )
    op.drop_index(
        "ix_ecs_challenge_tracker_owner_id", table_name="ecs_challenge_tracker"
    )
    op.drop_index("ix_ecs_challenge_tracker_ports", table_name="ecs_challenge_tracker")
    op.drop_index(
        "ix_ecs_challenge_tracker_revert_time", table_name="ecs_challenge_tracker"
    )
    op.drop_index(
        "ix_ecs_challenge_tracker_task_definition", table_name="ecs_challenge_tracker"
    )
    op.drop_index(
        "ix_ecs_challenge_tracker_timestamp", table_name="ecs_challenge_tracker"
    )
    op.drop_table("ecs_challenge_tracker")
    # ### end Alembic commands ###
