"""empty message

Revision ID: 6f2773029d86
Revises: b4fb43494ffc
Create Date: 2023-03-13 11:07:19.643247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "6f2773029d86"
down_revision = "b4fb43494ffc"
branch_labels = None
depends_on = None


def upgrade(op=None):
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ecs_challenge", sa.Column("flag_containers", sa.Text(), nullable=True)
    )
    op.add_column(
        "ecs_challenge",
        sa.Column("ssh_container", sa.String(length=128), nullable=True),
    )
    op.add_column(
        "ecs_challenge",
        sa.Column("vnc_container", sa.String(length=128), nullable=True),
    )
    op.drop_index("ix_ecs_challenge_entrypoint_container", table_name="ecs_challenge")
    op.drop_column("ecs_challenge", "entrypoint_container")
    # ### end Alembic commands ###


def downgrade(op=None):
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ecs_challenge",
        sa.Column(
            "entrypoint_container",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=128),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_ecs_challenge_entrypoint_container",
        "ecs_challenge",
        ["entrypoint_container"],
        unique=False,
    )
    op.drop_column("ecs_challenge", "vnc_container")
    op.drop_column("ecs_challenge", "ssh_container")
    op.drop_column("ecs_challenge", "flag_containers")
    # ### end Alembic commands ###
