"""Add filter tag column to the ECSConfig table

Revision ID: b4fb43494ffc
Revises: fd89efbba1d3
Create Date: 2023-03-09 12:08:10.946144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b4fb43494ffc"
down_revision = "fd89efbba1d3"
branch_labels = None
depends_on = None


def upgrade(op=None):
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ecs_config", sa.Column("filter_tag", sa.String(length=128), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade(op=None):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ecs_config", "filter_tag")
    # ### end Alembic commands ###
