"""Add launch type column to ECSChallenge

Revision ID: d636e6a85f63
Revises: 15277440466a
Create Date: 2023-03-07 09:38:56.226732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd636e6a85f63'
down_revision = '15277440466a'
branch_labels = None
depends_on = None


def upgrade(op=None):
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecs_challenge', sa.Column('launch_type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade(op=None):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ecs_challenge', 'launch_type')
    # ### end Alembic commands ###
